[theme]

# Primary accent for interactive elements
primaryColor = '#8DD9BF'  # Light Green

# Background color for the main content area
backgroundColor = '#28211E'  # Dark Brown

# Color used for almost all text
textColor = '#FFFFFF'  # White

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
