[theme]

# Primary accent for interactive elements
primaryColor = '#FFFFFF'  # White

# Background color for the main content area
backgroundColor = '#F5F5F5'  # Light Gray

# Color used for almost all text
textColor = '#28211E'  # Dark Brown

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false