[theme]

# Primary accent for interactive elements
primaryColor = '#00843D'  # UVU Green

# Background color for the main content area
backgroundColor = '#FFFFFF'  # White

# Color used for almost all text
textColor = '#004B28'  # Dark Green

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
